/**
 * APPLICATION CONTEXT - Demo Pest Control
 * Generated by AppShellGenerator v2.0 for app a0004000-0000-0000-0000-000000000001
 *
 * GATE 6, SECOND HALF. Mounting a component puts it on the page. onContext() is what lets it
 * reach a row. The shell hands each mounted component whatever window.AppContext holds, and
 * until 2026-08-03 NOTHING IN THIS ESTATE EVER SET IT -- the v4 wiring generator wrote an
 * app-init.js carrying exactly these keys, the v2 rewrite dropped it, and the shell was left
 * warning about a global no generator produced. Twelve components mounted and none fetched.
 *
 * THE CREDENTIALS ARE A DEPLOYMENT SEAM, NOT A GENERATION ONE. This file ships with the same
 * placeholders the v4 wiring used. Substitute them for the engine this deployment points at:
 *
 *     https://albuwrgidsoqpgywgjrg.supabase.co        -> e.g. http://127.0.0.1:54321  (Local)  or the project URL
 *     eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFsYnV3cmdpZHNvcXBneXdnanJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MzQ1NzcsImV4cCI6MjA3MjUxMDU3N30.MtlhhQ_IFylHGiG_34SNYaPLyY5bcnimrqYkxBD9bb4   -> the anon key for that engine
 *
 * The shell REFUSES TO PRETEND when they are still here: index.html preflights this file and
 * logs "CANNOT FETCH" naming the placeholders, rather than mounting twelve silent components.
 *
 * DO NOT EDIT the generated keys -- regenerate from the database instead.
 */

(function (window) {
    'use strict';

    window.AppContext = {

        // ---- the engine this app reads -------------------------------------------------
        //
        // `schema` comes from app_definitions.domain_schema. It is the app's OWN schema; a
        // component whose blueprint names a different one overrides it. Note the divergence,
        // deliberately not papered over here: list-view and detail-panel take the schema from
        // their BLUEPRINT (this.config.database.schema), form-crud takes it from THIS CONTEXT.
        // Two patterns, two sources for one fact -- see 06-blueprint-processing-gates.md.
        supabase: {
            url:     'https://albuwrgidsoqpgywgjrg.supabase.co',
            anonKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFsYnV3cmdpZHNvcXBneXdnanJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MzQ1NzcsImV4cCI6MjA3MjUxMDU3N30.MtlhhQ_IFylHGiG_34SNYaPLyY5bcnimrqYkxBD9bb4',
            schema:  'services_template'
        },

        // ---- who is asking ---------------------------------------------------------------
        //
        // Deployment defaults, carried forward from the v4 wiring generator. These are NOT
        // projected from the database: no table in app_factory says who is signed in. A real
        // deployment replaces them at the same moment it replaces the credentials above.
        // THE TENANT IS A SEAM MEMBER (s31, 2026-08-19). It was hardcoded 'default', and the
        // first app whose rows carry a real uuid tenant got a 400 on every fetch ("invalid
        // input syntax for type uuid"). Substitute at deploy time like the url and key:
        //     11111111-1111-1111-1111-111111111111 -> the tenant this deployment serves
        //                      (Local dogfood apps substitute the literal: default)
        tenant_id: '11111111-1111-1111-1111-111111111111',

        // OPTIONAL third-party capabilities (s31). Substituted only when a blueprint of this
        // app declares the capability; an unsubstituted value is not a preflight fault -- the
        // component that needs it warns at use time and proceeds degraded.
        //     __MAPBOX_TOKEN__ -> a publishable (pk.*) Mapbox token, URL-restricted in the
        //                         Mapbox account; read by geocode_on_save forms.
        integrations: {
            mapboxToken: '__MAPBOX_TOKEN__'
        },
        user_id:   'system',
        role:      'admin',
        locale:    'en-US',
        timezone:  'UTC',

        // WHICH PERSONA IS LOOKING. Read at RENDER time by every component that carries a persona
        // gate -- change it and the same screen shows a different set of fields, which is what a
        // demo switcher does and what signing in as a different user will do for real.
        //
        // A facet_code from app_factory.work_facets: ADMIN_FULL, OPS_MANAGER, SERVICE_MANAGER,
        // GENERIC_USER. null means NO NARROWING -- each screen shows its blueprint's own curation,
        // which is the honest default while the app has no sign-in.
        //
        // `role` above is NOT this. It is a free-text deployment default nothing reads; the gate
        // is keyed by facet_code and only facet_code.
        facet:     null
    };

})(window);
